kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-10gb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

